version: '3.8'

services:
  # Node.js application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=adityagaba
      - DB_PASSWORD=password
      - DB_NAME=clans_db
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=development
      - ENCRYPT_RESPONSES=false
      - ENCRYPTION_KEY=my-super-secret-encryption-key-123
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=http://localhost:3000/api/auth/google/callback
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev

  # PostgreSQL database
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=adityagaba
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=clans_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: